[package]
name = "dochy_bench"
version = "0.1.0"
authors = ["juzy <dochy.ksti@gmail.com>"]
edition = "2018"

[profile.test]
opt-level = 3

[dependencies]
dochy = { path = "../dochy" }
rand = "0.8.3"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
once_cell = "1.7.2"
